apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram
  labels:
    app: udagram
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram
  template:
    metadata:
      labels:
        app: udagram
    spec:
      containers:
        - name: udagram-feed
          image: monikma/udagram-feed
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
        - name: udagram-user
          image: monikma/udagram-user
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 80