apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram
  labels:
    app: udagram
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram
  template:
    metadata:
      labels:
        app: udagram
    spec:
      containers:
        - name: udagram-feed
          image: monikma/udagram-feed
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 82
          env:
            - name: POSTGRES_USERNAME
              value: "udagrammonikadev"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: dbpass
            - name: POSTGRES_HOST
              value: "udagrammonikadev.czwpmjfoijtu.us-east-2.rds.amazonaws.com"
            - name: POSTGRES_DB
              value: "udagrammonikadev"
            - name: AWS_BUCKET
              value: "test-126361239052-dev"
            - name: AWS_REGION
              value: "us-east-2"
            - name: AWS_PROFILE
              value: "default"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: jwt
            - name: URL
              value: "http://localhost:8100"
        - name: udagram-user
          image: monikma/udagram-user
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 81
          env:
            - name: POSTGRES_USERNAME
              value: "udagrammonikadev"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: dbpass
            - name: POSTGRES_HOST
              value: "udagrammonikadev.czwpmjfoijtu.us-east-2.rds.amazonaws.com"
            - name: POSTGRES_DB
              value: "udagrammonikadev"
            - name: AWS_BUCKET
              value: "test-126361239052-dev"
            - name: AWS_REGION
              value: "us-east-2"
            - name: AWS_PROFILE
              value: "default"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: jwt
            - name: URL
              value: "http://localhost:8100"