apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram
  name: udagram-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/udagram-svc
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: udagram
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
